image:
   name: "continuumio/miniconda3"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
   
before_script:
  - export PATH="/opt/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda create -q -n snakemake snakemake>=5.4.0
  # add additional stuff to setup below
  # e.g. make new environment, create index etc.

job:
  script:
    - source activate snakemake
    # run the workflow using test data:
    # you can add ngs-test-data in .gitmodules by:
    # git submodule add git@gitlab.com:schmeierlab/workflows/ngs-test-data.git
    - snakemake --use-conda --directory ngs-test-data
    - snakemake --use-conda --use-singularity --directory ngs-test-data
