$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  results:
    type: string
  samples:
    type: string
  units:
    type: string

required:
  - results
  - samples
  - units
